const blogArticle = [
  {
    id: 1,
    title: 'LES NOUVEAUTÉS DANS LA NOUVELLE VERSION PHP 8',
    dateArt: '3 février 2020',
    url: 'php.developpez.com',
    tags: '« PHP » / « Version » / « Web »',
    reference: 'SLAM 5, SI6',
    body: 'La nouvelle version du langage PHP est prévue pour décembre 2020 et apporte plusieurs nouvelles fonctionnalités. La nouvelle fonctionnalité JIT aura pour but de contourner la compilation, il serait en mesure d’apporter des améliorations considérables en termes de performances et d’utilisation de la mémoire. Aussi à partir de PHP 8, le type static devrait aussi devenir un type de retour valide.',
  },
  {
    id: 2,
    title:
      "QUELS SONT LES COÛTS LIÉS À L'UTILISATION DE FRAMEWORKS JAVASCRIPT POUR LE DÉVELOPPEMENT WEB ?",
    dateArt: '21 avril 2020 ',
    url: 'https://timkadlec.com/remembers/2020-04-21-the-cost-of-javascript-frameworks/',
    tags: '« JavaScript» / « Framework» / « Web »',
    reference: 'SLAM 5, SI6',
    body: 'Il est de plus en plus fréquent que les performances du Web baisse. Ceci a pour cause l’avènement des frameworks Web, comme React et Vue.js, et les applications qui privilégient les développeurs à l’expérience utilisateur. Ainsi le développeur Tim Kadlec à tester les performances des différents framework web pour en tirer conclusion que les frameworks JavaScripts alourdissent inexorablement les chargements surtout le premier chargement.',
  },
  {
    id: 3,
    title: 'PYTHON EST DÉSORMAIS PLUS POPULAIRE QUE JAVA',
    dateArt: '5 novembre 2020',
    url: 'https://www.tiobe.com/tiobe-index/',
    tags: '« Python » / « Langage» / « Java »',
    reference: 'SLAM 4, Algorithme Appliquée',
    body: "Python occupe la seconde place, la position la plus haute qu'il ait occupée dans le classement depuis 2001. Java ne fait pas partie du duo de tête pour la première fois en 20 ans. La récente montée en popularité de Python pourrait être due à des domaines en plein essor tels que l'exploration de données, l'IA et le calcul numérique. La popularité de Python est liée à la demande générale, les compétences en programmation sont nécessaires partout de nos jours et il y a un manque de bons développeurs de logiciels",
  },
  {
    id: 4,
    title: "LES NOUVEAUTÉS D'ANGULAR 11",
    dateArt: '16/11/2020',
    url: 'https://www.programmez.com/actualites/sortie-de-angular-11-31153',
    tags: '« JavaScript» / « Framework» / « Web »',
    reference: 'SLAM 5, SI6',
    body: "L'équipe de développement d'Angular a publié Angular 11, Angular est un Framework open source développé en JavaScript par Google.Dans cette nouvelle version on retrouves plusieurs améliorations des performances et nouvelles API.Il y a également des types plus stricts qui sont ajoutés pour DatePipe qui formate une valeur de date selon les règles locales.  Elle ajoute aussi de nouvelles fonctionnalités à Angular, comme le support de Webpack 5 ( Webpack regroupe des fichiers JavaScript pour les utiliser dans un navigateur).",
  },
  {
    id: 5,
    title:
      ' REDWOODJS : UN FRAMEWORK POUR DÉVELOPPER DES APPLICATIONS JAMSTACK',
    dateArt: '02/11/2020 ',
    url: 'https://www.lemondeinformatique.fr/actualites/lire-redwood-apporte-un-environnement-serverless-complet-a-jamstack-80935.html',
    tags: '« JavaScript» / « Framework» / « Web »',
    reference: 'SLAM 5, SI6',
    body: "Redwood est un framework d'applications Web sans serveur qui permet de créer et de déployer facilement des applications JAMstack. Le framework possède une interface React, fournie de manière statique par CDN, qui communique, via GraphQL,  avec le backend fonctionnant sur AWS Lambdas .La pile de Redwood comprend React , GraphQL, Prisma , Babel , Webpack. D'autres bibliothèques devraient venir prochainement s'y ajouter. Redwood s'appuie sur Jamstack, une architecture de développement Web basée sur JavaScript côté client, des API réutilisables et un balisage prédéfini. JAMstack est l'acronyme de JavaScript, APIs et Markup. Cela veut dire que contrairement à un CMS comme WordPress, le serveur web ne fait que livrer des fichiers statiques pré-compilés.",
  },
  {
    id: 6,
    title: 'PHP 7.2 : LA FIN DU SUPPORT (EOL) EST FIXÉE AU 30 NOVEMBRE 2020',
    dateArt: '02/11/2020',
    url: 'https://www.ionos.fr/digitalguide/sites-internet/developpement-web/php-72/',
    tags: '« PHP » / « Version » / « Web »',
    reference: 'SLAM 5, SI6',
    body: 'À l’automne 2017, la version PHP 7.2 a été publiée pour faire suite à PHP 7.1. L’une des grandes nouveautés était la bibliothèque cryptographique Sodium qui a été intégrée au noyau de PHP. Le 30 novembre 2020, cette version atteindra également la date officielle d’end of life (EOL), et ne sera plus supportée. Les statistiques de distribution de PHP montrent que le code PHP obsolète n’est souvent pas mis à jour. De nombreux utilisateurs semblent en effet ne pas procéder à la migration et craignent des problèmes techniques lors du changement. Le manque de temps est une autre raison de reporter les mises à jour techniquement en retard ou les mises à jour de versions majeures.',
  },
  {
    id: 7,
    title: 'PLATFORM.SH LANCE UNE PLACE DE MARCHÉ DE FRAMEWORKS',
    dateArt: '02/11/2020',
    url: 'https://www.lemondeinformatique.fr/actualites/lire-databricks-livre-sql-analytics-pour-requeter-sur-les-data-lakes-81044.html',
    tags: '« Framework» / « PaaS» / « Web »',
    reference: 'SLAM 5, SI7',
    body: "Platform.sh est une PaaS  (Plateform As A Service) . Avec cette plateforme, le  développeur peut se concentrer uniquement sur son travail en faisant abstraction de l'infrastructure technique et des opérations systèmes. ",
  },
  {
    id: 8,
    title: 'STOCKAGE DANS LES APPLICATIONS WEB',
    dateArt: '01/07/2020',
    url: 'https://www.youtube.com/watch?v=NNuTV-gjlZQ&list=PLNYkxOF6rcIBhuGsbO6t8-OBE5-fVPe7K',
    tags: '« Stockage» / « Data» / « Web »',
    reference: 'SLAM 5, SI6',
    body: "Pete Lepage a présenté sur web.dev LIVE une description des options dont disposent les développeurs pour stocker et mettre en cache les données sur le client. Web.dev LIVE est un événement communautaire en ligne de trois jours parrainé par Google et consacré à l'état du développement Web.  CacheStorage, StorageManager et d'autres API aident les développeurs à créer des applications avec des capacités hors ligne. Pour stocker et mettre en cache une quantité importante de données structurées,  les développeurs peuvent utiliser ces API de stockage de cache qui sont pris en charge dans tous les navigateurs. La quantité maximale de données pouvant être stockées dans le navigateur varie selon le fournisseur de navigateur. Certains navigateurs peuvent définir une limite en pourcentage de l'espace disque disponible. Lorsqu'ils atteignent les limites de quota, les développeurs peuvent adopter quelques stratégies pour libérer de l'espace: supprimer l'ancien contenu, supprimer du contenu volumineux ou déléguer la décision de supprimer à l'utilisateur.",
  },
  {
    id: 9,
    title:
      "BLOOMBERG ENGINEERING PARTAGE SES EXPÉRIENCES D'ADOPTION DE TYPESCRIPT DANS UNE LARGE BASE DE CODE",
    dateArt: '17/11/2020 ',
    url: 'https://www.infoq.com/news/2020/11/bloomberg-typescript-adoption/',
    tags: '«Architecture» / « TypeScript» / « Migration »',
    reference: 'SLAM 5, SI7',
    body: "La très grande entreprise Bloomberg Engineering  à commencer un processus d’adoption de TypeScript à grande échelle.C’est un langage qui a pour but d'améliorer et de sécuriser la production de code JavaScript. Il s'agit d'un sur-ensemble de la syntaxe. Cet exemple de migration peut être utile pour toute grande base de code passant à TypeScript. Ce processus de migration visait à respecter des normes et à maintenir une productivité de développement élevée même lorsque la base de code TypeScript se développait. L’objectif est de bénéficier des améliorations de typage, de stabilité et de vitesse qui coïncident généralement avec les nouvelles versions de TypeScript. Elles peuvent cependant interrompre le processus de construction en faisant apparaître des erreurs de type précédemment non détectées. L'adoption de TypeScript continue d’augmenter et les responsables technologiques peuvent apprendre des stratégies de migration, des processus et des outils adoptés par les grandes entreprises.",
  },
  {
    id: 10,
    title: 'ELECTRON, LE FRAMEWORK EST DISPONIBLE EN VERSION 11.0',
    dateArt: '23/11/2020',
    url: 'https://web.developpez.com/actu/310650/Electron-le-framework-pour-le-developpement-des-apps-multiplateformes-de-bureau-avec-HTML-CSS-et-JS-est-disponible-en-version-11-0-et-integre-desormais-le-support-de-l-architecture-ARM64-d-Apple/',
    tags: '« Framework» / « Multi-Plateforme» / « Web »',
    reference: 'SLAM 5, SI6',
    body: "Electron est un environnement permettant de développer des applications multi-plateformes de bureau avec des technologies web (JavaScript, HTML et CSS). L'infrastructure (backend) est codée en node.js, et l'interface frontend est bâtie sur les outils Chromium, la partie open source de Google Chrome. Electron est un logiciel libre open source développé par GitHub. D’après leur site ce framework a permis de développer Visual Studio Code par exemple. La nouveauté qui intervient dans cette dernière version d'Électron est la prise en charge de la nouvelle architecture de processeur ARM sur laquelle sont basés les ordinateurs Mac d’Apple qui viennent de sortir. En effet les développeurs peuvent donc utiliser Electron 11 pour recompiler leurs applications pour ARM64 afin de tirer profit de tous les avantages de la nouvelle architecture d’Apple.",
  },
  {
    id: 11,
    title: 'REACT V17',
    dateArt: '26 octobre 2020',
    url: 'https://javascript.developpez.com/actu/313061/jQuery-3-6-0-est-disponible-mais-la-bibliotheque-JavaScript-est-elle-encore-beaucoup-utilisee-en-2021/',
    tags: '« JavaScript» / « React» / « Framework »',
    reference: 'SLAM 5, SLAM 4',
    body: "La librairie JavaScript de Facebook est un des framework JavaScript les plus en vue depuis notamment sa version 16 et l’introduction des hooks sortie en 2017. En dépit de la promesse faite par les développeurs de faire de cette mise à jour une avancée importante, les changements surtout côté développeurs sont faibles. Cependant, l'objectif principal de cette version est de s'assurer qu'il est sûr d'incorporer un composant géré par une version de React dans un composant géré par une autre version. Quand React 18 va sortir, les composants de cette version pourront fonctionner avec React 17.",
  },
  {
    id: 12,
    title: "MALGRÉ JQUERY 3.6 , UN DÉBUT D'OBSOLESCENCE POUR JQUERY ?",
    dateArt: '3 mars 2021',
    url: 'https://www.developpez.net/forums/d2104550/',
    tags: ' « JavaScript»  / « Framework » ',
    reference: 'SLAM 5, SLAM 4',
    body: "Dans cette nouvelle version il n’y a pas de correctif de sécurité, mais contient de bonnes corrections de bugs et des améliorations mais l’objectif des développeurs reste la version jQuery 4.0. Malgré ces perspectives d’évolution la pertinence de jQuery est mise en doute. On distingue que certains développeurs ont commencé à prendre de la distance vis-à-vis de la bibliothèque JavaScript. C'est le cas par exemple de l'équipe Bootstrap qui abandonne jQuery pour du pur JavaScript dans la version 5.0 du framework t. Le principal argument avancé pour justifier la suppression de jQuery dans Bootstrap v5 est que maintenant que plus de 95 % des fonctionnalités de jQuery sont désormais natives dans les navigateurs donc ajouter une dépendance JS serait superflue.",
  },
  {
    id: 13,
    title: 'LE FRAMEWORK INERTIA.JS :',
    dateArt: '04 décembre 2020 ',
    url: 'https://www.infoq.com/news/2020/12/inertia-modern-monolith/',
    tags: '« JavaScript» / « Framework » ',
    reference: 'SLAM 5',
    body: "Inertia.js permet aux développeurs d'écrire des applications d'une seule page (Single Page App) à l'aide du routage et des contrôleurs classiques côté serveur. Inertia rapproche le backend et frontend afin que les développeurs n'aient pas besoin d'écrire des API. Les développeurs peuvent utiliser des frameworks côté serveur par exemple, Laravel, Ruby on Rails, Django. Sur le client, les développeurs peuvent utiliser React, Svelte ou Vue pour implémenter l'interface utilisateur. Inertia.js permet aux développeurs de créer des applications Web comme s'ils suivaient une architecture page multiple  (MPA). Les développeurs exploitent une infrastructure Web côté serveur pour le routage, l'authentification, l'autorisation, la récupération de données, etc. La vue est cependant à la charge du client, comme dans les SPA.",
  },
  {
    id: 14,
    title: 'REACT NATIVE V 0.64 :',
    dateArt: '12 mars 2021 ',
    url: 'https://reactnative.dev/blog',
    tags: '« JavaScript» / « React» / « Framework » ',
    reference: ' SLAM 5, SLAM 4',
    body: "Le 12 mars 2021 React Native 0.64 a  été publié et cette version est  livrée avec la prise en charge d'Hermes sur iOS. Hermes est un moteur JavaScript open source optimisé pour exécuter React Native. Il améliore les performances en diminuant l'utilisation de la mémoire, en réduisant la taille du téléchargement et en diminuant le temps nécessaire à l'application pour devenir utilisable. Cette mise à jour prend aussi compte de la dernière version de React (React 17). En effet les fichiers de l'application n’ont plus besoin d’importer React pour utiliser du JSX dans les fichiers.",
  },
  {
    id: 15,
    title:
      'NETLIFY: UN HÉBERGEMENTS QUI SE DÉMARQUE POUR LE DÉVELOPPEMENT WEB JAMSTACK',
    dateArt: ' 24 Février 2021',
    url: 'https://www.prnewswire.com/news-releases/netlify-named-among-most-promising-private-companies-in-2021-enterprise-tech-30-301234224.html',
    tags: '« Hébergement» / « DevOps» / « Framework »',
    reference: ' SLAM 5, SLAM 4',
    body: "Netlify est devenu l’hébergeur avec des fonctionnalités gratuites les plus intéressantes dans le développement de site JamStack , c'est-à- dire sans le contenu partie serveur de l’application. Un site Web statique reste le même après chaque visite, contrairement au contenu dynamique où il change. Votre serveur génère ces fichiers statiques et les renvoie aux navigateurs. Ces sites Web peuvent récupérer des données de presque n'importe où, y compris des API, des CMS et d'autres fichiers de contenu. Avec Netlify, on peut publier des projets Web à partir d’un Git sans configuration complexe ni maintenance de serveur. Automatisez les processus d’intégration continue  pour les développeurs Web. Vous pouvez même prévisualiser l'ensemble du site pour voir à quoi ressemble votre site Web avant de le publier.",
  },
  {
    id: 16,
    title: "MONGODB: L'ESSOR DES BASES DE DONNÉES NOSQL",
    dateArt: '24 Février 2021',
    url: 'https://www.infoworld.com/article/3611403/forget-databases-you-need-a-data-platform.html',
    tags: '« Base de données» / « DevOps» ',
    reference: 'SLAM 5, SLAM 4, SLAM 3',
    body: "Le directeur technique de MongoDB, l’évolution du stockage de données ne se fera plus par des centres de données mais par des plateformes.capable de traiter, stocker, sécuriser et analyser les données en temps réel, sur tous les ensembles de données pertinents. On peut observer , on voit augmenter le nombre de développeurs qui abandonnent les technologies SQL. On voit ensuite que les bases NoSQL sont migrées vers le cloud plus rapidement que leurs équivalents SQL. Cependant, MongoDB constate que la majorité des utilisateurs préfèrent des options non payantes, y compris des éditions gratuites de MongoDB, des services d'hébergement cloud gratuits et des outils gratuits pour travailler avec les données MongoDB. En 2020, seuls 23% de ses utilisateurs s’étaient tournés vers Atlas ou vers l’édition Enterprise.",
  },
  {
    id: 17,
    title: 'NEXT.JS 10',
    dateArt: '17 Janvier 2021',
    url: 'https://medium.com/swlh/is-next-js-10-really-awesome-bf82c7c8dbd',
    tags: '« React» / « DevOps» / « Framework »',
    reference: 'SLAM 5, SLAM 4',
    body: "NEXT JS est un framework qui facilite l’écriture d’applications React universelles et vous permet d’intégrer de belles fonctionnalités telles que le routage simple des pages ou l’exportation statique du site. L'intérêt des frameworks JS tels que Next Js, Nuxt ou Gatsby est d'avoir le backend et le frontend dans la même architecture ainsi le système de routes peut être basé sur les fichiers.Next JS par exemple se base sur le file system node pour définir les routes frontend et backend de votre application. Pour chaque fichier JavaScript présent dans le répertoire Pages, Next JS crée la route frontend du même nom. Next.js 10 a présenté Next.js Analytics. Cette nouvelle solution permet de suivre les performances du monde réel et de réintégrer ces informations dans votre dans l’environnement de développement. Il mesure maintenant en continu et les mesures sur votre appareil de développement, les mesures proviendront des appareils réels que les visiteurs utilisent.",
  },
  {
    id: 18,
    title:
      'HEROKU: UN HÉBERGEMENTS QUI SE DÉMARQUE POUR LE DÉVELOPPEMENT WEB JAMSTACK',
    dateArt: '27 janvier 2021',
    url: 'https://blog.heroku.com/news',
    tags: '« DataBase» / « DevOps»',
    reference: 'SLAM 5, SLAM 3',
    body: "Heroku est une PaaS (plateforme en tant que service) permettant de déployer des applications sur le Cloud. A la façon dont un hébergeur web propose d’héberger un site web sur ses propres serveurs, cette solution vous permet de déployer votre application sur le Cloud pour permettre aux internautes de l’utiliser. Heroku Postgres est désormais 40 fois plus rapide en exploitant les instantanés à la place des sauvegardes de base. Nous avons travaillé dur pour améliorer les performances, la vitesse et la capacité des services Heroku Data sur lesquels vous comptez. Dans le passé, les fourchettes et les suivis d'une base de données de test Premium-8 avec 992 Go de données prenaient 22 heures; maintenant avec les instantanés, le même processus est réduit à 10 minutes. Cela rend la création de fourches et d'adeptes et la restauration de la base de données plus rapides que jamais, sans frais supplémentaires. Heroku propose une expérience simple et intuitive. Il s’agit aussi d’une plateforme ouverte et extensible, permettant aux développeurs d’utiliser le langage de programmation de leur choix : Nodejs, Ruby, PHP, Python, Java…On compte par ailleurs de nombreux add-ons Heroku permettant d’ajouter davantage de fonctionnalités à une application en un seul clic.",
  },
  {
    id: 19,
    title: 'JEE: QUELS SONT LES PERSPECTIVES POUR L’AVENIR',
    dateArt: '25 janvier 2021 ',
    url: 'https://www.infoq.com/fr/articles/microprofile-jakarta-ee-2021/?itm_source=articles_about_development&itm_medium=link&itm_campaign=development',
    tags: '« Framework »/ « JEE» ',
    reference: 'SLAM 5, SLAM 3',
    body: "Le premier point est la Fondation Eclipse.La Fondation Eclipse est un espace d'innovation, de collaboration et un processus qui garantit que toute cette propriété intellectuelle sera liée à l'open source. Un autre point important est les nouvelles spécifications qui ont tendance à entrer dans la famille Jakarta EE cette année. Il s'agira de: Jakarta MVC : une spécification MVC au sein de Jakarta EE Jakarta NoSQL : la première spécification née au sein de Jakarta EE. Elle vise à faciliter l'intégration entre le monde Java et NoSQL. Il est possible de percevoir une grande perspective pour l'avenir de J2E. La transparence et la collaboration sont deux des fondements  de la Fondation Eclipse. Parmi les points en discussion pour cette année, les points forts seront certainement la migration vers Java 11, l'union et le réglage des deux projets, la définition de savoir si les projets auront plus de modules ou s'ils seront plus ciblés, en plus de bien d'autres choses ! La meilleure partie est que tout le monde dans la communauté Java peut participer et créer l'avenir au lieu de simplement le regarder. ",
  },
  {
    id: 20,
    title:
      'ROR : RUBY 3 EST DISPONIBLE, UNE VERSION MAJEURE ANNONCÉE COMME ÉTANT TROIS FOIS PLUS RAPIDE QUE RUBY 2',
    dateArt: '25 janvier 2021',
    url: 'https://www.infoq.com/fr/articles/microprofile-jakarta-ee-2021/?itm_source=articles_about_development&itm_medium=link&itm_campaign=development',
    tags: '« Framework » / « ROR »',
    reference: 'SLAM 5, SLAM 3',
    body: "Ruby est le plus souvent utilisé pour créer des applications Web. Cependant, il s'agit d'un langage à usage général similaire à Python, il a donc de nombreuses autres applications. L'implémentation probablement la plus évidente de Ruby est Ruby On Rails, le framework de développement construit avec Ruby. Ruby, Python, et PHP sont probablement les trois langages les plus utilisés en Back End. Cependant, Ruby on Rails perd de sa popularité, et il y a trois raisons à cela : Rapidité, Mise à l'échelle et Flexibilité. Ainsi, la nouvelle version de ruby souhaite relancer son langage avec un gain de rapidité introduit par JIT, le compilateur en temps réel.  JIT est censé améliorer les performances des charges de travail limitées ou toute autre application qui passe la majorité du temps à appeler plusieurs méthodes plusieurs fois. Bien que Ruby 3.0 ait réduit la taille du code JIT, il n'est toujours pas prêt pour l'optimisation des charges de travail comme Rails, qui passent souvent du temps sur tant de méthodes. Ces changements sont attendu dans la version 3.1",
  },
]

export default blogArticle
